project:
  type: website
  output-dir: docs

website:
  title: "Detección de cuentas falsas"
  navbar:
    left:
      - href: index.qmd
        text: Intro
      - href: analisis_exploratorio.qmd
        text: Análisis Exploratorio
      - visualizacion.qmd
      - reglas_asociacion.qmd
      - href: FCA.qmd
        text: FCA
      - regresion.qmd
      - series_temporales.qmd
      - summary.qmd
      - references.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

